# Generated by Django 6.1.1 on 2026-09-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_donation_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional. Captured from mobile SDK donations for audit.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_image/'),
        ),
    ]
