# Generated by Django 6.1.1 on 2026-09-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_donation_phone_alter_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='checkout_link',
            field=models.URLField(blank=True, help_text='Chapa checkout URL used for this payment.', max_length=500, null=True),
        ),
    ]
