# Generated by Django 6.1.1 on 2026-09-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_donation_checkout_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='return_url',
            field=models.URLField(blank=True, help_text='Return URL we sent to Chapa — for audit and debugging.', max_length=500, null=True),
        ),
    ]
